feat: Include multiple markers as a single layer && made js file and apply html file
GEOor/GEOor pull request #4
Opened 2022-05-09 02:14 UTC by suhwan-cheon

**1. openlayers 에서 vectorlayer를 생성 후 source에 feature들을 넣는 방식으로 다중 마커 기능을 구현하였습니다.**

<img width="430" alt="image" src="https://user-images.githubusercontent.com/52690419/167328286-2d9051a0-66aa-46ea-864f-d31e8dd28427.png">

openlayers 구조와 모든 feature의 id가 달라야한다는 점 등 문제가 좀 있었는데,, 다담주 발표는 내가 하는걸로,,  

**2. javascript 파일 따로 옮겨뒀습니다.**

html 에서 js 적용 코드보면 defer 옵션을 달아뒀는데, DOM이 생성된 후에 js 코드를 실행 할 수 있게 해준다고 함
이번에 처음 써봤는데, async 문제 해결 및 개발자 의도대로 코드 수행이 가능해서 최근 권장하는 방법이라고 하는듯..  

**3. 잡다한 파일, 고칠 부분 주석처리 해뒀습니다.**

버리려고했는데, 필요한 코드길래 프로그램 실행 가능할 정도로만 만들어뒀습니다.  

**4. 터널, 교량 정보들 db 저장 방법**

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/52690419/167328802-51b9291f-238c-4d61-9fd8-fb8ab08f6c0d.png">

dsm파일 db 저장법과 동일하게 geor database 만들고 bridge, tunnel 이라는 이름의 테이블 생성 후
위에있는 hsService.run() 코드 주석처리 빼면 들어가질거에요. 테스트를 안했는데 안되면

![image](https://user-images.githubusercontent.com/52690419/167329024-df062ddd-fb3d-4188-87ca-b551feb566d8.png)

2022-05-11 11:31 UTC, kimtaehyun98 reviewed
👍👍👍

2022-05-11 11:31 UTC, kimtaehyun98 commented on src/main/java/geo/hs/controller/SunController.java
> +//    private ArrayList<ArrayList<SunInfo>> sunInfoArr = new ArrayList<ArrayList<SunInfo>>();
안 쓸것 같은 코드면 시원하게 삭제하는 것도 좋을 듯??
어차피 다른 레포도 있어서 복구 가능이니까

2022-05-11 11:31 UTC, kimtaehyun98 commented on src/main/resources/templates/WMS.html
> +    <script src="wms.js" defer></script>
defer는 처음 보는데 신기하네 😁

2022-05-11 17:13 UTC, brorica requested changes
필요 없는 주석 지우거나 수정하고 다시 pr 하는게 좋을 거 같아요

2022-05-11 17:13 UTC, brorica commented on src/main/java/geo/hs/service/HillShadeService.java
> +//		 2021-11-22
주석에 작성자나 날짜명 내용 보단 메소드에 대해 간략한 설명만 있는게 좋을거 같아요

2022-05-12 00:03 UTC, suhwan-cheon commented on src/main/java/geo/hs/controller/SunController.java
> +//    private ArrayList<ArrayList<SunInfo>> sunInfoArr = new ArrayList<ArrayList<SunInfo>>();
넵

2022-05-12 00:03 UTC, suhwan-cheon commented on src/main/java/geo/hs/controller/SunController.java
> +//                ArrayList<SunInfo> si = crawler.get();
네 크롤러 코드가 바꼈다고하네요!

2022-05-12 07:06 UTC, merged